"""Download cat-searcher/minif2f-lean4 and write LeanDojo-style JSON for ReProver.

Each problem must reference a traced .lean file under data/minif2f_reprover/project/.
Row order from Hugging Face matches MiniF2FGen/minif2f_{val|test}_NNNN.lean layout.
"""

import json
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = REPO_ROOT / "data"
PROJECT_DIR = DATA_DIR / "minif2f_reprover" / "project"


def _git_head(repo: Path) -> str:
    return subprocess.check_output(
        ["git", "-C", str(repo), "rev-parse", "HEAD"],
        text=True,
    ).strip()


def write_minif2fgen_root_lean() -> None:
    """Emit MiniF2FGen.lean with one import per problem file.

    Lake only builds modules reachable from a library root. Without these imports,
    val/test problems are never compiled, LeanDojo finds no per-file *.ast.json,
    and Dojo fails with "Cannot find the *.ast.json file".
    """
    lines = [
        "-- Auto-generated by scripts/setup_minif2f_example.py.",
        "-- Imports every problem module so Lake produces per-file .olean / .ast.json.",
        "",
    ]
    for split in ("val", "test"):
        d = PROJECT_DIR / "MiniF2FGen" / split
        if not d.is_dir():
            continue
        for f in sorted(d.glob("minif2f_*.lean")):
            stem = f.stem
            lines.append(f"import MiniF2FGen.{split}.{stem}")
    root = PROJECT_DIR / "MiniF2FGen.lean"
    root.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _build_records(rows: list, split_prefix: str, split_label: str) -> list:
    project_url = str(PROJECT_DIR.resolve())
    commit = _git_head(PROJECT_DIR)
    records = []
    for i, row in enumerate(rows):
        pid = row["id"]
        file_path = f"MiniF2FGen/{split_prefix}/minif2f_{split_prefix}_{i:04d}.lean"
        informal_stmt = row.get("informal_stmt") or row.get("nl_statement") or ""
        informal_proof = row.get("informal_proof") or row.get("nl_proof") or ""
        records.append(
            {
                "id": pid,
                "file_path": file_path,
                "full_name": pid,
                "start": [19, 1],
                "split": split_label,
                "source": "cat-searcher/minif2f-lean4",
                "informal_stmt": informal_stmt,
                "informal_proof": informal_proof,
                "url": project_url,
                "commit": commit,
            }
        )
    return records


def main() -> None:
    from datasets import load_dataset

    if not PROJECT_DIR.is_dir():
        print(
            f"error: expected traced Lean project at {PROJECT_DIR}",
            file=sys.stderr,
        )
        sys.exit(1)
    try:
        _git_head(PROJECT_DIR)
    except subprocess.CalledProcessError:
        print(
            f"error: {PROJECT_DIR} is not a git checkout (need HEAD for LeanDojo)",
            file=sys.stderr,
        )
        sys.exit(1)

    dataset = load_dataset("cat-searcher/minif2f-lean4")
    hf_val_key = "validation" if "validation" in dataset else "valid"
    val_rows = list(dataset[hf_val_key])
    test_rows = list(dataset["test"])

    DATA_DIR.mkdir(parents=True, exist_ok=True)
    with open(DATA_DIR / "val.json", "w", encoding="utf-8") as f:
        json.dump(_build_records(val_rows, "val", "val"), f, indent=2)
        f.write("\n")
    with open(DATA_DIR / "test.json", "w", encoding="utf-8") as f:
        json.dump(_build_records(test_rows, "test", "test"), f, indent=2)
        f.write("\n")

    write_minif2fgen_root_lean()

    print(
        "Wrote data/val.json and data/test.json (LeanDojo format; paths under minif2f_reprover/project)."
    )
    print(
        "Note: The bundled Lean project is pinned to Lean 4.12 + mathlib v4.12.0 so LeanDojo's "
        "ExtractData.lean compiles. After git pull, re-run this script so val.json/test.json "
        "pick up the current project commit."
    )
    print(
        "Regenerated MiniF2FGen.lean (imports all problems). In data/minif2f_reprover/project, "
        "run `lake build`, commit the changes, then re-run this script so data/*.json get the new "
        "commit hash. Remove ~/.cache/lean_dojo/gitpython-project-<old-commit> if tracing was cached "
        "without per-file ast.json."
    )


if __name__ == "__main__":
    main()
